#include "mainwindow.h"
#include <QApplication>
#include <QPushButton>

#include "hackwifi.h"

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;                           //70 10 20 //nice red
    //w.setStyleSheet("background-color:rgb(70, 10, 20);color:white;");



    std::stringstream cout;
    air::init(cout);
    cout << "\nSelect one of the tabs above to get started.\n";

    //noob section description
    cout << "Capture:(Only recommended if you want to go fast and dirty)\n";
    cout << "Linear Deauth Attack: Takes you to the noob attack screen.\n";
    cout << "   Does the following in sequence\n";
    cout << "      1: Scan wifi\n      2: Gets info on your interface\n      3: Lets you choose which AP to attack\n";
    cout << "      4: Performs a generic Deauth attack\n      5: Captures Handshake\n\n";
    //crack section description
    cout << "Crack:(Crack handshake files)\n";
    cout << "Crack Handshake: Attempts to crack handshake files generated by this program\n";
    cout << "   Does the following in sequence:\n      1. Searches for wordlists\n      2: Generates a list of APs with captured handshakes\n      3: Attempts crack on command\n";
    w.writeToMainText(cout.str());
    cout.clear();

    //connect functions

    w.show();
    return a.exec();
}
